### ISSUE TITLE
XML Rendering issue

### ISSUE THREAD

**Issue by Cayburn** [i-akiya/R4DSXML#3]
Hi, if you have time, can you please check why the following two public available define.xml files cannot be parsed correctly (https://github.com/phuse-org/phuse-scripts/tree/master/data/adam/TDF_ADaM_v1.0)?

```
library(R4DSXML)

file <- "C:/temp/git/phuse-scripts/data/adam/TDF_ADaM_v1.0/define.xml"
file <- "C:/temp/git/phuse-scripts/data/sdtm/TDF_SDTM_v1.0/define.xml"

#Get dataset level metadata
dataset.metadata <- getDLMD(file)

#Get variable level metadata
variable.metadata <- getVarMD(file)

#Get value level metadata
value.metadata <- getValMD(file)

#Get Controlled Terminology
ct.metadata <- getCT(file)
```

**Comment by i-akiya** [comment]
I'm really apologize for my response is long time delayed, because I did't check this repository until today.

I found following issue on getValMD function for your adam define.xml.
`
value.metadata <- getValMD(file)
Error in merge(ItemRef, item_def, by.x = "IR_ItemOID", by.y = "ID_OID") : 
  object 'ItemRef' not found
`
Your adam define.xml does not include "def:ValueListDef". Probably, it is the cause of this error.
